booksite/booksite/urls.py
# -*- coding: utf-8 -*-
# from django.views.generic.base import TemplateView
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from booksite.usercenter.views import ChangePWDView
from booksite.sitemap import BookSitemaps

admin.autodiscover()

usercenter_urls = patterns('booksite.usercenter.views',
                           url(r'^bookmark/$', 'bookmark', name='bookmark'),
                           url(r'^bookmark/(?P<bookmark_id>\d+)/read/(?P<page_number>\d+)/$',
                               'bookmark_read', name='bookmark_read'),
                           url(r'^bookmark/add/$', 'add_bookmark', name='add_bookmark'),
                           url(r'^bookmark/(?P<bookmark_id>\d+)/delete/$', 'del_bookmark', name='del_bookmark'),
                           url(r'^changepwd/$', ChangePWDView.as_view(), name='changepwd'),
                           )

html5_urls = patterns('',
                      url(r'^$', 'booksite.book.views.mb_index', name='mb'),
                      url(r'^load/$', 'booksite.book.views.mb_load', name='mb_load'),
                      url(r'^search/$', 'booksite.book.views.mb_search', name='mb_search'),
                      url(r'^searchload/$', 'booksite.book.views.mb_searchload', name='mb_searchload'),
                      url(r'^login/$', 'booksite.usercenter.views.mb_login', name='mb_login'),
                      url(r'^logout/$', 'booksite.usercenter.views.mb_logout', name='mb_logout'),
                      url(r'^bookmark/$', 'booksite.usercenter.views.mb_bookmark', name='mb_bookmark'),
                      url(r'^book/(?P<book_id>\d+)/$', 'booksite.book.views.mb_bookindex', name='mb_bookindex'),
                      url(r'^page/(?P<page_number>\d+)/$', 'booksite.book.views.mb_bookpage', name='mb_bookpage'),
                      )

background_urls = patterns('booksite.background.views',
                           url(r'^$', 'index', name="home"),
                           url(r'^replace/$', 'replace', name="replace"),
                           url(r'^replace/delete/(?P<pk>\d+)/$', 'delete_rule', name="delete_rule"),
                           url(r'^replace/edit/(?P<pk>\d+)/$', 'edit_rule', name="edit_rule"),
                           url(r'^replace/apply/(?P<pk>\d+)/$', 'apply_rule', name="apply_rule"),
                           url(r'^replace/page/$', 'replace_page', name="replace_page"),
                           url(r'^replace/book/$', 'replace_book', name="replace_book"),
                           url(r'^tuijian/$', 'tuijian', name="tuijian"),
                           url(r'^tuijian/create/fengtui/$', 'fengtui_create', name="fengtui_create"),
                           url(r'^tuijian/create/jingtui/$', 'jingtui_create', name="jingtui_create"),
                           url(r'^tuijian/delete/(?P<model>ft|jt)/(?P<book_id>\d+)/$',
                               'del_tuijian', name="del_tuijian"),
                           url(r'^booksearch/$', 'book_search', name="book_search"),
                           url(r'^booksearch/jx/$', 'book_jx', name="book_jx"),
                           url(r'^booksearch/ft/$', 'book_ft', name="book_ft"),
                           url(r'^booksearch/jt/$', 'book_jt', name="book_jt"),
                           url(r'^booksearch/jxall/$', 'book_jiuzhenggengxin', name="book_jiuzhenggengxin"),
                           url(r'^booksearch/pagezipper/$', 'book_page_next_zipper', name="book_page_next_zipper"),
                           )

password_reset_urls = patterns('',
                               url(r'^$',
                                   'django.contrib.auth.views.password_reset',
                                   {
                                       'template_name': 'usercenter/password_reset_form.jade',
                                       'email_template_name': 'usercenter/password_reset_email.html',
                                   },
                                   name='password_reset'
                                   ),
                               url(r'^done/$',
                                   'django.contrib.auth.views.password_reset_done',
                                   {'template_name': 'usercenter/password_reset_done.jade'},
                                   name='password_reset_done'
                                   ),
                               url(r'^confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$',
                                   'django.contrib.auth.views.password_reset_confirm',
                                   {'template_name': 'usercenter/password_reset_confirm.jade'},
                                   name='password_reset_confirm'
                                   ),
                               url(r'^complete/$',
                                   'django.contrib.auth.views.password_reset_complete',
                                   {'template_name': 'usercenter/password_reset_complete.jade'},
                                   name='password_reset_complete'
                                   ),
                               )

sitemaps = {
    'books': BookSitemaps,
}

urlpatterns = patterns('',
                       url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
                           name='django.contrib.sitemaps.views.sitemap'),
                       # url(r'^sitemap\.xml$', 'booksite.baidusitemap.views.sitemap', {'sitemaps': sitemaps}, name='sitemap'),
                       url(r'^$', 'booksite.book.views.home', name='home'),
                       url(r'^fenlei/(?P<category>[a-z])/$', 'booksite.book.views.category', name='category'),
                       url(r'^bookrank/$', 'booksite.book.views.bookrank', name='bookrank'),
                       url(r'^booknews/$', 'booksite.book.views.booknews', name='booknews'),
                       url(r'^book/(?P<book_id>\d+)/$', 'booksite.book.views.bookindex', name='bookindex'),
                       url(r'^bookinfo/(?P<book_id>\d+)/$', 'booksite.book.views.bookinfo', name='bookinfo'),
                       url(r'^bookindex/(?P<book_id>\d+)/$', 'booksite.book.views.bookindexajax', name='bookindexajax'),
                       url(r'^page/(?P<page_number>\d+)/$', 'booksite.book.views.bookpage', name='bookpage'),

                       url(r'^nallpage/(?P<page_id>\d+)/$', 'booksite.book.views.load_nall_page', name='nallpage'),
                       url(r'^fixpic/page/(?P<page_id>\d+)/$', 'booksite.book.views.page_fix_pic', name='pagefixpic'),
                       url(r'^fixpic/book/(?P<book_id>\d+)/$', 'booksite.book.views.book_fix_pic', name='bookfixpic'),
                       url(r'^taskcheck/page/(?P<page_id>\d+)/$',
                           'booksite.book.views.page_task_check', name='pagetaskcheck'),
                       url(r'^lineupdate/$', 'booksite.book.views.edit_line', name="lineupdate"),
                       url(r'^lineremove/(?P<page_id>\d+)/$', 'booksite.book.views.del_line', name="del_line"),

                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^usercenter/', include(usercenter_urls)),
                       url(r'^login/$', 'booksite.usercenter.views.login_view', name='login'),
                       url(r'^signup/$', 'booksite.usercenter.views.signup', name='signup'),
                       url(r'^logout/$', 'booksite.usercenter.views.logout_view', name='logout'),
                       url(r'^captcha/', include('captcha.urls')),

                       url(r'^resetpassword/', include(password_reset_urls)),

                       url(r'^mobile/', include(html5_urls)),

                       url(r'^bbg/', include(background_urls, namespace='bbg', app_name='booksite.background')),
                       )

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += patterns('',
                            url(r'^media/book/(?P<path>.*)$', 'booksite.book.views.bookpage_zip', name='zippage')
                            )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booksite/booksite/background/models.py
# -*- coding: utf-8 -*-
import re
import hashlib
import cPickle as pickle
import time
import itertools
from booksite.book.models import KeyValueStorage, Book


class GetRuleError(Exception):
    pass


class ReplaceRule(object):
    KEY_PREFIX = "replace_rule_"

    def __init__(self, rule_res, replace_to):
        self.rule_res = rule_res
        self.replace_to = replace_to
        self.hash = self.get_hash()
        self.db_data = KeyValueStorage()
        self.db_data.key = ReplaceRule.KEY_PREFIX + str(int(time.time()))
        self.db_data.val = {
            "rule_res": self.rule_res,
            "replace_to": self.replace_to
        }

    def __str__(self):
        return unicode(self).encode("utf-8")

    def __unicode__(self):
        try:
            return u"'%s' -> '%s'" % (
                self.rule_res.decode("utf-8"),
                self.replace_to.decode("utf-8"),
            )
        except:
            return u"'%s' -> '%s'" % (
                self.rule_res,
                self.replace_to,
            )

    def get_hash(self):
        pickle_data = pickle.dumps([self.rule_res, self.replace_to])
        return hashlib.sha256(pickle_data).hexdigest()

    def replace(self, content, flags=0):
        rex = re.compile(self.rule_res, flags)
        return rex.sub(self.replace_to, content)

    def findall(self, content, flags=0):
        rex = re.compile(self.rule_res, flags)
        return rex.findall(content)

    def match(self, content, flags=0):
        rex = re.compile(self.rule_res, flags)
        return rex.search(content)

    @classmethod
    def make_rule(cls, db_obj):
        rule = cls(db_obj.val["rule_res"], db_obj.val["replace_to"])
        rule.db_data = db_obj
        rule.hash = db_obj.value
        return rule

    @classmethod
    def all(cls):
        all_rule_data = KeyValueStorage.objects.filter(key__startswith=cls.KEY_PREFIX).order_by("-key")
        iter_data = itertools.imap(
            cls.make_rule,
            all_rule_data
        )
        return iter_data

    @classmethod
    def get(cls, pk=0):
        if not pk:
            raise GetRuleError("primary key error! primary key[%s]" % pk)
        try:
            db_data = KeyValueStorage.objects.get(pk=pk)
        except KeyValueStorage.DoesNotExist:
            raise GetRuleError("DoesNotExist! primary key[%s]" % pk)
        else:
            return cls.make_rule(db_data)

    def save(self):
        self.db_data.val = {
            "rule_res": self.rule_res,
            "replace_to": self.replace_to
        }
        self.db_data.save()

    def delete(self):
        if self.db_data.pk:
            self.db_data.delete()


class ImplementError(BaseException):
    pass


class TuiJianObj(object):

    def __init__(self):
        if not hasattr(self, 'KEY'):
            raise ImplementError('TuiJianObj need inherit.')
        ft_data, created = KeyValueStorage.objects.get_or_create(key=self.KEY)
        if created:
            self.book_id_list = []
        else:
            self.book_id_list = ft_data.val or []
        self.books = self._build_books()

    def _build_books(self):
        books = []
        for book_id in self.book_id_list:
            try:
                books.append(Book.objects.get(id=book_id))
            except Book.DoesNotExist:
                pass
        return books

    def __str__(self):
        return unicode(self).encode("utf-8")

    def __unicode__(self):
        return "|".join(self.books.objects.values_list("title", flat=True))

    def add(self, book):
        self.book_id_list.append(book.id)
        self.books.append(book)

    def remove(self, book):
        if book.id in self.book_id_list:
            self.book_id_list.remove(book.id)
            self.books = self._build_books()

    def save(self):
        data = KeyValueStorage.objects.get_or_create(key=self.KEY)[0]
        data.val = self.book_id_list
        data.save()


class FengTui(TuiJianObj):
    KEY = "fengtui"


class JingTui(TuiJianObj):
    KEY = "jingtui"

booksite/booksite/background/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django import forms
from booksite.book.models import BookPage, Book
from .models import ReplaceRule, FengTui, JingTui


class TuiJianForm(forms.Form):
    book_id = forms.CharField(label="书名", max_length=50, required=True)

    def __init__(self, model=FengTui, *args, **kwargs):
        super(TuiJianForm, self).__init__(*args, **kwargs)
        if model not in (FengTui, JingTui):
            raise TypeError("model not in (FengTui, JingTui)!")
        self.tuijian_model = model

    def clean_book_id(self):
        try:
            book = Book.objects.get(title=self.cleaned_data['book_id'])
        except Book.DoesNotExist:
            raise forms.ValidationError("Book does not exist!")
        self.book = book
        return self.cleaned_data['book_id']

    def save(self):
        if self.is_valid():
            tuijian = self.tuijian_model()
            tuijian.add(self.book)
            tuijian.save()
        else:
            raise forms.ValidationError()


class ReplaceRuleCreateForm(forms.Form):
    rule_res = forms.CharField(label="匹配表达式", max_length=256)
    replace_to = forms.CharField(label="替换为", max_length=256, required=False)

    def save(self):
        if self.is_valid():
            new_rule = ReplaceRule(
                self.cleaned_data['rule_res'].encode('utf-8'),
                self.cleaned_data['replace_to'].encode('utf-8'),
            )
            new_rule.save()
        else:
            raise forms.ValidationError()


class ReplaceBookApplyForm(forms.Form):
    SELECT = (
        ('preview', "预览"),
        ('save', "保存"),
    )
    rule_res = forms.CharField(label="匹配表达式", max_length=256)
    replace_to = forms.CharField(label="替换为", max_length=256, required=False)
    book_id = forms.CharField(label="书籍编号", max_length=10)
    p_or_s = forms.ChoiceField(choices=SELECT, widget=forms.RadioSelect)

    def get_rule(self):
        if self.is_valid():
            return ReplaceRule(
                self.cleaned_data['rule_res'],
                self.cleaned_data['replace_to'],
            )
        else:
            raise forms.ValidationError()

    def get_book(self):
        if self.is_valid():
            return Book.objects.get(pk=self.cleaned_data['book_id'])
        else:
            raise forms.ValidationError()


class ReplacePageApplyForm(forms.Form):
    SELECT = (
        ('preview', "预览"),
        ('save', "保存"),
    )
    rule_res = forms.CharField(label="匹配表达式", max_length=256)
    replace_to = forms.CharField(label="替换为", max_length=256, required=False)
    page_number = forms.CharField(label="章节编号", max_length=10)
    p_or_s = forms.ChoiceField(choices=SELECT, widget=forms.RadioSelect)

    def get_rule(self):
        if self.is_valid():
            return ReplaceRule(
                self.cleaned_data['rule_res'],
                self.cleaned_data['replace_to'],
            )
        else:
            raise forms.ValidationError()

    def get_page(self):
        if self.is_valid():
            return BookPage.objects.get(page_number=self.cleaned_data['page_number'])
        else:
            raise forms.ValidationError()

booksite/booksite/background/templates/background/base.html
{% load static %}
{% load assets %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
	<title>看小说么? -- 后台管理{% spaceless %}{% block pagetitle %}{% endblock pagetitle %}{% endspaceless %}</title>
	<link rel="stylesheet" href="{% static 'bootstrap3/css/bootstrap.min.css' %}">
	{# {% assets "css_all_bkg" %} #}
		{# <link href="{{ ASSET_URL }}" rel="stylesheet"> #}
	{# {% endassets %} #}
	<link rel="stylesheet" href="{% static 'botspmd/css/material.css' %}">
	<link rel="stylesheet" href="{% static 'botspmd/css/ripples.css' %}">
	<link rel="stylesheet" href="{% static 'css/background.css' %}">
	{% block headercss %}
	{% endblock headercss %}
	<script src="{% static 'flatui/js/jquery-1.8.3.min.js' %}"></script>
	{% block headerjs %}
	<script>var DATA_DIC = DATA_DIC || {}</script>
	{% endblock headerjs %}

</head>
<body class="inv">
{% spaceless %}
	<nav class="navbar navbar-inverse" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
				</button>
				<a class="navbar-brand" href="/">看小说,么?</a>
			</div>
			<div class="collapse navbar-collapse" id="navbar-collapse-1">
				<ul class="nav navbar-nav main">
					<li class="dropdown" id="nav-category">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">分类阅读{%if category%}:{{category}}{%endif%}<span class="caret"></span></a>
						<span class="hidden-xs dropdown-arrow dropdown-arrow-inverse"></span>
						<ul class="dropdown-menu dropdown-inverse" role="menu">
							{% for ca in categorys %}
								{% if ca.name %}<li id="nav{{ca.key}}"><a href="{% url 'category' ca.key %}">{{ca.name}}</a></li>{% endif %}
							{% endfor %}
						</ul>
					</li>
					<li id="navp">
						<a href="{% url 'bookrank' %}">排行榜</a>
					</li>
					{% if user.is_superuser %}
					<li class="active">
						<a href="{% url 'bbg:home' %}">管理后台</a>
					</li>
					{% endif %}
				</ul>
				<ul class="nav navbar-nav navbar-right">
					{% if user.is_authenticated %}
					<li class="dropdown">
						<a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown">个人中心<span class="caret"></span></a>
						<span class="hidden-xs dropdown-arrow dropdown-arrow-inverse"></span>
						<ul class="dropdown-menu dropdown-inverse" role="menu">
							<li><a href="javascript:;">{{user.username}}</a></li>
							<li><a href="{% url 'changepwd' %}">修改密码</a></li>
							<li id="navbma"><a href="{% url 'bookmark' %}">我的书架</a></li>
							<li class="divider"></li>
							<li><a href="{% url 'logout' %}">登出</a></li>
						</ul>
					</li>
					{% else %}
					<li><a href="{% url 'login' %}">登录</a></li>
					<li><a href="{% url 'signup' %}">注册</a></li>
					{% endif %}
				</ul>
				<form class="navbar-form navbar-right" action="/" method="get" role="search">
					<input name="s" class="form-control col-lg-8 empty" type="search" placeholder="搜索书籍标题" />
				</form>
			</div>
		</div>
	</nav>
{% endspaceless %}
	<div class="container" style="min-height: 300px;">
		<div class="col-xs-2">
			<div class="lnav affix">
				<ul class="nav nav-pills nav-stacked">
					<li class="active"><a href="{% url 'bbg:home' %}">数据总览</a></li>
					<li id="lnav-replace"><a href="{% url 'bbg:replace' %}">内容替换</a></li>
					<li id="lnav-tuijian"><a href="{% url 'bbg:tuijian' %}">推荐书籍</a></li>
					<li id="lnav-booksearch"><a href="{% url 'bbg:book_search' %}">书籍搜索</a></li>
				</ul>
			</div>
		</div>
		<div class="col-xs-10 no-padding">
		{% block content %}{% endblock content %}
		</div>
	</div>
	{% block footerblock %}{% endblock footerblock %}
	<footer class="bs-docs-footer inv">
		<div class="container text-center">
			<p>本网站由<a href="http://twitter.com/ouyanghongyu" target="_blank">@ouyanghongyu</a>设计与制作.</p>
			<p>更多信息请查看<a href="https://github.com/tkliuxing/bookspider">我的GitHub</a>.</p>
			<p>本项目源码受 <a href="https://github.com/tkliuxing/bookspider/blob/master/LICENSE" target="_blank">Apache</a> 开源协议保护. 本站收录文章版权归原作者所有.</p>
			<ul class="bs-docs-footer-links muted">
				<li>当前版本： v1.0</li>
				<li>·</li>
				<li><a href="https://github.com/tkliuxing/bookspider">GitHub 仓库</a></li>
				<li>·</li>
				<li><a href="https://github.com/tkliuxing/bookspider/issues?state=open">Issues</a></li>
			</ul>
		</div>
	</footer>
	{% assets "js_all_bkg" %}
		<script src="{{ ASSET_URL }}" rel="stylesheet"></script>
	{% endassets %}
	{% block footerjs %}
	{% endblock footerjs %}
</body>
</html>